// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLFHO6brGuD2jLCD3-IZb1yWcTm5OWPs',
    appId: '1:889846027815:web:184cf98b5ca3051ead6002',
    messagingSenderId: '889846027815',
    projectId: 'neulbo-915ae',
    authDomain: 'neulbo-915ae.firebaseapp.com',
    databaseURL: 'https://neulbo-915ae-default-rtdb.firebaseio.com',
    storageBucket: 'neulbo-915ae.appspot.com',
    measurementId: 'G-PKXGSVBCLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbaUdulm5iWgbF6rSjcbw_qSOCEFt2YE8',
    appId: '1:889846027815:android:23f0342280dce655ad6002',
    messagingSenderId: '889846027815',
    projectId: 'neulbo-915ae',
    databaseURL: 'https://neulbo-915ae-default-rtdb.firebaseio.com',
    storageBucket: 'neulbo-915ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPH_ugGFzcZmmgYfBntMeBEbAw7v5-Dks',
    appId: '1:889846027815:ios:1a8cc523ad5ca843ad6002',
    messagingSenderId: '889846027815',
    projectId: 'neulbo-915ae',
    databaseURL: 'https://neulbo-915ae-default-rtdb.firebaseio.com',
    storageBucket: 'neulbo-915ae.appspot.com',
    iosClientId: '889846027815-qsk84mlgm8qpntma5ebirho7baa8i64s.apps.googleusercontent.com',
    iosBundleId: 'com.example.neulbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPH_ugGFzcZmmgYfBntMeBEbAw7v5-Dks',
    appId: '1:889846027815:ios:1a8cc523ad5ca843ad6002',
    messagingSenderId: '889846027815',
    projectId: 'neulbo-915ae',
    databaseURL: 'https://neulbo-915ae-default-rtdb.firebaseio.com',
    storageBucket: 'neulbo-915ae.appspot.com',
    iosClientId: '889846027815-qsk84mlgm8qpntma5ebirho7baa8i64s.apps.googleusercontent.com',
    iosBundleId: 'com.example.neulbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLFHO6brGuD2jLCD3-IZb1yWcTm5OWPs',
    appId: '1:889846027815:web:1f4636d205e6f2c4ad6002',
    messagingSenderId: '889846027815',
    projectId: 'neulbo-915ae',
    authDomain: 'neulbo-915ae.firebaseapp.com',
    databaseURL: 'https://neulbo-915ae-default-rtdb.firebaseio.com',
    storageBucket: 'neulbo-915ae.appspot.com',
    measurementId: 'G-CD1WHSTNR1',
  );

}